import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>App Devuar puedes ver mis cambios 😺</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Develter.js!</a>
        </h1>
        <nav className="timeline">
          <Link href="/timeline">Timeline </Link>
        </nav>
      </main>

      {/* <footer className={styles.footer}></footer> */}

      <style jsx>
        {`
          h1 {
            color: red;
          }

          nav {
            font-size: 24px;
            text-align: center;
          }

          .richard {
            color: green;
          }
        `}
      </style>
    </>
  );
}
